### ISSUE TITLE
新版的目录问题

### ISSUE THREAD

**Issue by dcy** [xinmingZhou/stackEdit#1]
你好！
我也一直使用stackedit，旧版使用[TOC]就可以生成目录了。新版说要使用Templates里面的Styled HTML with TOC。不会用这个，请问你知道新版https://stackedit.io/app 如何生成目录么？

**Comment by xinmingZhou** [comment]
你好，最新版我也没试过，不过我检查了一下好像这是付费功能。
![84c6d0c9-e156-4f73-883b-8c22cc3882f7](https://user-images.githubusercontent.com/20434365/35657537-f06bbc64-0737-11e8-9c2c-69f45078a397.png)

**Comment by dcy** [comment]
那不是付费功能的意思，它弹框基本都有这个，只是建议赞助它
